name: copo

d_feature: 128            # ======================================================= Number of output channels of the backbone = costvolume_unet_feat_dim
num_depth_candidates: 128 #128?
num_surfaces: 1

visualizer:
  num_samples: 8
  min_resolution: 256
  export_ply: true

gaussians_per_pixel: 1
gaussian_adapter:
  gaussian_scale_min: 0.5
  gaussian_scale_max: 15.0
  sh_degree: 2 # 4

opacity_mapping:
  initial: 0.0
  final: 0.0
  warm_up: 1

# params for multi-view depth predictor
copo_weights_path: "checkpoints/eloftr_outdoor.ckpt"
costvolume_unet_feat_dim: 128 # = d_feature
costvolume_unet_channel_mult: [1,1,1]
costvolume_unet_attn_res: []
depth_unet_feat_dim: 64
depth_unet_attn_res: []
depth_unet_channel_mult: [1, 1, 1]
downscale_factor: 4 # CNN features must be restored to the original image size  =======================================================
shim_patch_size: 4

n_view: 2
n_points: 64
num_hidden_units_phi: 128

# below are ablation settings, keep them as false for default model
wo_depth_refine: false         # Table 3: base
wo_cost_volume: false          # Table 3: w/o cost volume
wo_backbone_cross_attn: false  # Table 3: w/o cross-view attention
wo_cost_volume_refine: false   # Table 3: w/o U-Net



