defaults:
  - view_sampler: bounded

name: re10k
# roots: [datasets/re10k]
roots: [/usr/stud/chj/storage/user/chj/datasets/re10k_subset]
make_baseline_1: false
augment: true

# H, W must be divided by 32, and h must be greater than 200=self.TRAIN_PAD_NUM_GT_MIN 
# image_shape: [180, 320]
# image_shape: [160, 320]
# image_shape: [224, 320]
image_shape: [256, 256]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

baseline_epsilon: 1e-3
max_fov: 100.0

skip_bad_shape: true
near: 1.
far: 100.
baseline_scale_bounds: false
shuffle_val: true
test_len: -1
test_chunk_interval: 1
